version: '2'
services:
  activity:
    #dockerfile: ./activity/Dockerfile
    image: activity

  activity2:
    #dockerfile: ./activity2/Dockerfile
    image: activity2

  proxy:
    image: ng
    ports:
     - "80:8888"
    links:
     - activity
     - activity2

   
